baseurl: 'https://username.github.io'
DefaultContentLanguage: en  # https://gohugo.io/content-management/multilingual/
title: Beautiful Hugo
theme: beautifulhugo
metaDataFormat: yaml
#disqusShortname: XXX  # Enter your disqus shortname
#googleAnalytics: XXX  # Enter your Google Analytics Tracking ID

markup:
  goldmark:
    renderer:
      unsafe: true  # Enable rendering HTML tags in markdown
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 4

enableGitInfo: false  # Enable in conjunction with `Params: commit:`

Params:
  # homeTitle: Beautiful Hugo Theme  # Set a different text for the header on the home page
  subtitle: Build a beautiful and simple website in minutes
  mainSections:
    - post
    - posts
  logo: img/avatar-icon.png  # Expecting square dimensions
  favicon: img/favicon.ico
  dateFormat: 'January 2, 2006'  # https://gohugo.io/functions/dateformat/
  # commit: "https://github.com/<username>/<siterepo>/tree/"  # Show commit sha in the footer - Also add `enableGitInfo: true` above `Params:`
  rss: true
  comments: true  # Enables a comment section below each post
  readingTime: true  # Shows reading time above post excerpt
  wordCount: true  # Shows word count above post excerpt
  useHLJS: false  # Client side highlighting using highlight.js - overrides Hugo's Chroma engine
  socialShare: true
  delayDisqus: true  # Only load Disqus after clicking a "Show Comments" button
  showRelatedPosts: true
  hideAuthor: false
#  gcse: '012345678901234567890:abcdefghijk'
#  bigimg:
#    - src: img/triangle.jpg
#      desc: Triangle
#    - src: img/sphere.jpg
#      desc: Sphere
#      position: center top
#    - src: img/hexagon.jpg
#      desc: Hexagon

  imports:
    css:
      - url: https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css
        integrity: sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh
      - url: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css
        integrity: sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=
      - url: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css
        integrity: sha256-V8SV2MO1FUb63Bwht5Wx9x6PVHNa02gv8BgH/uH3ung=
      - url: https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.css
        integrity: sha256-LWdHSKWG7zv3DTpee8YAgoTfkj3gNkfauF624h4P2Nw=
      - url: https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/default-skin/default-skin.min.css
        integrity: sha256-Q9bBMw/rHRRag46GDWY84J3elDNc8JJjKXL9tIC4oe8=
      - url: https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic
      - url: https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800
    js:
      - url: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js
        integrity: sha256-F/Xda58SPdcUCr+xhSGz9MA2zQBPb0ASEYKohl8UCHc=
      - url: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/contrib/auto-render.min.js
        integrity: sha256-90d2pnfw0r4K8CZAWPko4rpFXQsZvJhTBGYNkipDprI=
      - url: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js
        integrity: sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=
      - url: https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js
        integrity: sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6
      - url: https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js
        integrity: sha256-ePwmChbbvXbsO02lbM3HoHbSHTHFAeChekF1xKJdleo=
      - url: https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js
        integrity: sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=


# The items below enable footer icons for each service, and will generate the appropriate links.
Author:
  name: Some Person
  website: yourwebsite.com
  email: youremail@domain.com
  facebook: username
  github: username
  gitlab: username
  bitbucket: username
  twitter: username
  reddit: username
  linkedin: username
  xing: username
  stackoverflow: users/XXXXXXX/username
  snapchat: username
  instagram: username
  youtube: user/username
  soundcloud: username
  spotify: username
  bandcamp: username
  itchio: username
  vk: username
  paypal: username
  telegram: username
  500px: username
  codepen: username
  mastodon: url
  kaggle: username
  weibo: username
  slack: username

menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - identifier: samples
      name: Samples
      weight: 2
    - parent: samples
      name: Big Image Sample
      url: post/2017-03-07-bigimg-sample
      weight: 1
    - parent: samples
      name: Math Sample
      url: post/2017-03-05-math-sample
      weight: 2
    - parent: samples
      name: Code Sample
      url: post/2016-03-08-code-sample
      weight: 3
    - name: Tags
      url: tags
      weight: 3
