baseurl: 'https://username.github.io'
DefaultContentLanguage: en  # https://gohugo.io/content-management/multilingual/
title: Beautiful Hugo
theme: beautifulhugo
metaDataFormat: yaml
#disqusShortname: XXX  # Enter your disqus shortname
#googleAnalytics: XXX  # Enter your Google Analytics Tracking ID

markup:
  goldmark:
    renderer:
      unsafe: true  # Enable rendering HTML tags in markdown
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 4

enableGitInfo: false  # Enable in conjunction with `Params: commit:`

Params:
  # homeTitle: Beautiful Hugo Theme  # Set a different text for the header on the home page
  subtitle: Build a beautiful and simple website in minutes
  mainSections:
    - post
    - posts
  logo: img/avatar-icon.png  # Expecting square dimensions
  favicon: img/favicon.ico
  dateFormat: 'January 2, 2006'  # https://gohugo.io/functions/dateformat/
  # commit: "https://github.com/<username>/<siterepo>/tree/"  # Show commit sha in the footer - Also add `enableGitInfo: true` above `Params:`
  rss: true
  comments: true  # Enables a comment section below each post
  readingTime: true  # Shows reading time above post excerpt
  wordCount: true  # Shows word count above post excerpt
  useHLJS: false  # Client side highlighting using highlight.js - overrides Hugo's Chroma engine
  socialShare: true
  delayDisqus: true  # Only load Disqus after clicking a "Show Comments" button
  showRelatedPosts: true
  hideAuthor: false
#  gcse: '012345678901234567890:abcdefghijk'
#  bigimg:
#    - src: img/triangle.jpg
#      desc: Triangle
#    - src: img/sphere.jpg
#      desc: Sphere
#      position: center top
#    - src: img/hexagon.jpg
#      desc: Hexagon

# The items below enable footer icons for each service, and will generate the appropriate links.
Author:
  name: Some Person
  website: yourwebsite.com
  email: youremail@domain.com
  facebook: username
  github: username
  gitlab: username
  bitbucket: username
  twitter: username
  reddit: username
  linkedin: username
  xing: username
  stackoverflow: users/XXXXXXX/username
  snapchat: username
  instagram: username
  youtube: user/username
  soundcloud: username
  spotify: username
  bandcamp: username
  itchio: username
  vk: username
  paypal: username
  telegram: username
  500px: username
  codepen: username
  mastodon: url
  kaggle: username
  weibo: username
  slack: username

menu:
  main:
    - name: Blog
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - identifier: samples
      name: Samples
      weight: 2
    - parent: samples
      name: Big Image Sample
      url: post/2017-03-07-bigimg-sample
      weight: 1
    - parent: samples
      name: Math Sample
      url: post/2017-03-05-math-sample
      weight: 2
    - parent: samples
      name: Code Sample
      url: post/2016-03-08-code-sample
      weight: 3
    - name: Tags
      url: tags
      weight: 3
